update web3 data changed callback
AlphaWallet/TokenScript pull request #394
Opened 2020-10-10 23:48 UTC by James-Sangalli

https://github.com/AlphaWallet/alpha-wallet-ios/pull/2161

2020-10-11 08:06 UTC, hboon requested changes
Also needs changes like this https://github.com/AlphaWallet/alpha-wallet-ios/pull/2161/files#diff-21eeed1f14eca84e42fe18b15a229ae9L67

2020-10-12 05:03 UTC, James-Sangalli commented
> Also needs changes like this https://github.com/AlphaWallet/alpha-wallet-ios/pull/2161/files#diff-21eeed1f14eca84e42fe18b15a229ae9L67

Thanks @hboon, updated.

2020-10-12 05:07 UTC, hboon requested changes
A few more. I just did a quick pass. See if they are right.

2020-10-12 05:07 UTC, hboon commented on ERCs/ERC20/layouts/item-view-approvalObtained.en.js
> +            <span><bold><h3>Approved to move ${this.props.card.amount} ${this.props.token.symbol} from ${this.props.from}</h3></bold></span>
`this.props.from` should be `this.props.card.from`

2020-10-12 05:07 UTC, hboon commented on ERCs/ERC20/layouts/item-view-ownerApproved.en.js
> +            <span><bold><h3>Gave approval to move ${this.props.card.amount} ${this.props.token.symbol} to ${this.props.to}</h3></bold></span>
`this.props.to` should be `this.props.card.to`

2020-10-12 05:07 UTC, hboon commented on ERCs/ERC20/layouts/receivedApproval.en.js
> +            <p>Approved to move ${this.props.card.amount} ${this.props.token.symbol} from ${this.props.from}</p>
`this.props.from` should be `this.props.card.from`

2020-10-12 05:07 UTC, hboon commented on ERCs/ERC721/layouts/item-view-sent.en.js
> +            <span><bold><h3>Sent ${this.props.token.symbol} tokenId: ${this.props.tokenId}</h3></bold></span>
`this.props.tokenId` should be `this.props.token.tokenId`

2020-10-12 05:07 UTC, hboon commented on ERCs/ERC721/layouts/receivedApproval.en.js
> +            <p>Approved to move tokenId: ${this.props.token.tokenId} ${this.props.token.symbol} from ${this.props.from}</p>
`this.props.from` should be `this.props.card.from`

2020-10-12 05:25 UTC, James-Sangalli commented
@hboon sorry, should be good now!

2020-10-12 05:32 UTC, hboon approved these changes

2020-10-12 05:33 UTC, hboon commented
Good to merge. Thanks!

2020-10-12 05:59 UTC, merged